### PR TITLE
Minor fixes (fix #51, fix #47)

### LINKED ISSUE #47: polish settings
- pixel perfect on the screens
- selecting again the same value shouldn't trigger a save like it's currently the case
- just a thought, but IMO it would be great to have a spinner on the left of the account name (left nav) to show that the update is in progress (think how to solve that in connectData, mmh, optimistic updates & stuff? xD).
- if there are a lot of accounts, we need to have SCROLL on the left sections.

### LINKED ISSUE #51: fix Dashboard piechart opacity glitch
capture d ecran 2017-12-06 a 20 26 23

### PR DESCRIPTION
**Pull request by malikfassi**

### CODE REVIEW

File: src/containers/Dashboard/PieChart.js [hunk 1]
```diff
@@ -4,14 +4,8 @@ import React, { Component } from "react";
 import * as d3 from "d3";
 import CurrencyAccountValue from "../../components/CurrencyAccountValue";
 import BadgeCurrency from "../../components/BadgeCurrency";
+import type { PieChartData } from "../../data/types";
 import "./PieChart.css";
-import type { Account } from "../../data/types";
-
-type PieChartData = {
```
Comment (gre) [inline src/containers/Dashboard/PieChart.js]: actually this is the correct place IMO :)

File: src/data/types.js [hunk 2]
```diff
@@ -168,3 +169,8 @@ export type OperationEntity = OperationCommon & {
   notes: NoteEntity[]
 };
 
+export type PieChartData = {
```
Comment (gre) [inline src/data/types.js]: (not in the data type model)
